"""
build_standalone.py
-------------------
Reads well_locations.json and embeds it directly into well_map.html,
producing a fully self-contained well_map_standalone.html that:
  - Works when opened locally as a file (file:// URL)
  - Works when uploaded to S3 as a single object (no public GeoJSON needed)
  - Works when hosted on GitHub Pages

Also uploads to:
  s3://osu-well-records-225989338968/viewer/well_map_standalone.html
  (private — access via presigned URL or AWS Console)

Usage:
  python build_standalone.py            # build local only
  python build_standalone.py --upload   # build + upload to S3 + print URL
"""

import boto3, json, os, sys

BUCKET   = "osu-well-records-225989338968"
REGION   = "us-east-1"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_JSON = os.path.join(BASE_DIR, "well_locations.json")
TEMPLATE  = os.path.join(BASE_DIR, "well_map.html")
OUT_HTML  = os.path.join(BASE_DIR, "well_map_standalone.html")
S3_KEY    = "viewer/well_map_standalone.html"


def main():
    upload = "--upload" in sys.argv

    # Load data
    if not os.path.exists(DATA_JSON):
        print(f"ERROR: {DATA_JSON} not found. Run merge_well_locations.py first.")
        sys.exit(1)

    print(f"Loading {DATA_JSON}...", flush=True)
    with open(DATA_JSON, "r", encoding="utf-8") as f:
        geojson = json.load(f)

    count = len(geojson.get("features", []))
    print(f"  {count:,} well locations loaded.", flush=True)

    # Load HTML template
    with open(TEMPLATE, "r", encoding="utf-8") as f:
        html = f.read()

    # Replace the async fetch with inline data injection
    # Find the loadData function and replace it with an inline version
    inline_script = f"""
// ─── Inline data (generated by build_standalone.py) ──────────────────────────
const INLINE_GEOJSON = {json.dumps(geojson, separators=(',', ':'))};

async function loadData() {{
  const detail = document.getElementById("load-detail");
  try {{
    detail.textContent = "Loading {count:,} embedded well locations...";
    const geojson = INLINE_GEOJSON;
    allFeatures = geojson.features || [];
    detail.textContent = `Rendering ${{allFeatures.length.toLocaleString()}} markers...`;

    if (geojson.generated) {{
      document.getElementById("data-updated").textContent =
        new Date(geojson.generated).toLocaleString();
    }}

    populateDropdowns(allFeatures);
    buildLegend();
    buildCountyList(allFeatures);
    updateStats(allFeatures);
    renderMarkers(allFeatures);

    if (allFeatures.length > 0) {{
      const lats = allFeatures.map(f => f.geometry.coordinates[1]);
      const lons = allFeatures.map(f => f.geometry.coordinates[0]);
      map.fitBounds([
        [Math.min(...lats)-0.3, Math.min(...lons)-0.3],
        [Math.max(...lats)+0.3, Math.max(...lons)+0.3]
      ]);
    }}

    const loading = document.getElementById("loading");
    loading.style.opacity = "0";
    setTimeout(() => loading.style.display = "none", 300);

  }} catch (err) {{
    document.getElementById("load-detail").textContent = `Error: ${{err.message}}`;
    console.error(err);
  }}
}}
"""

    # Replace existing loadData function block in the HTML
    # Splice right before initMap() call at the end of the script
    html = html.replace(
        "// ─── Data loading ─────────────────────────────────────────────────────────────\nasync function loadData()",
        "// ─── Data loading (REPLACED BY build_standalone.py) ─────────────────────────\n/* INLINE */ async function loadData_REPLACED()"
    )

    # Inject inline script right before </script>
    html = html.replace(
        "// ─── Boot ─────────────────────────────────────────────────────────────────────",
        inline_script + "\n// ─── Boot ─────────────────────────────────────────────────────────────────────"
    )

    # Update the subtitle to note it's standalone
    html = html.replace(
        "Historical oil &amp; gas well permits 1911–2024",
        f"Historical oil &amp; gas well permits 1911–2024 · {count:,} verified locations"
    )

    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(html)

    size_mb = os.path.getsize(OUT_HTML) / (1024 * 1024)
    print(f"✅ Standalone HTML: {OUT_HTML}  ({size_mb:.1f} MB)", flush=True)
    print(f"   Open in browser: file:///{OUT_HTML.replace(chr(92), '/')}", flush=True)

    if upload:
        s3 = boto3.client("s3", region_name=REGION)
        with open(OUT_HTML, "rb") as f:
            s3.put_object(Bucket=BUCKET, Key=S3_KEY, Body=f, ContentType="text/html")
        # Generate 7-day presigned URL
        url = s3.generate_presigned_url(
            "get_object",
            Params={"Bucket": BUCKET, "Key": S3_KEY},
            ExpiresIn=604800  # 7 days
        )
        print(f"\n🔗 Presigned URL (7 days):\n   {url}\n", flush=True)

        # Also save presigned URL to file
        with open(os.path.join(BASE_DIR, "viewer_url.txt"), "w") as f:
            f.write(url + "\n")
        print(f"   URL saved to visualizer/viewer_url.txt", flush=True)

    return OUT_HTML


if __name__ == "__main__":
    main()
